USE [master]
GO

/****** Object:  Database [meteodata]    Script Date: 10/03/2018 16:28:28 ******/
CREATE DATABASE [meteodata]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'meteodata', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\meteodata.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'meteodata_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\meteodata_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [meteodata] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [meteodata].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [meteodata] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [meteodata] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [meteodata] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [meteodata] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [meteodata] SET ARITHABORT OFF 
GO

ALTER DATABASE [meteodata] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [meteodata] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [meteodata] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [meteodata] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [meteodata] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [meteodata] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [meteodata] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [meteodata] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [meteodata] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [meteodata] SET  DISABLE_BROKER 
GO

ALTER DATABASE [meteodata] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [meteodata] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [meteodata] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [meteodata] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [meteodata] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [meteodata] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [meteodata] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [meteodata] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [meteodata] SET  MULTI_USER 
GO

ALTER DATABASE [meteodata] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [meteodata] SET DB_CHAINING OFF 
GO

ALTER DATABASE [meteodata] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [meteodata] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [meteodata] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [meteodata] SET QUERY_STORE = OFF
GO

USE [meteodata]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [meteodata] SET  READ_WRITE 
GO

